### ISSUE TITLE
[Question] Is there any way to show Notifications?

### ISSUE THREAD

**Issue by pegasuspect** [aaaeka/browser-screen-time#1]
Hi Emilis,
This is a great project, and its open source. So, I am grateful for all the effort that goes in here!

I was wondering if its possible to make a settings page where I can opt-in to notifications for specific websites. 

Apart from tracking how much time I spent, I would also be reminded at certain intervals, like if I spent too much time on YouTube in 1 day, for every hour I spent I could get a notification. Something similar was available for Xbox One.

This would require additional work. Defining 3 inputs to collect opt-in flag, the interval of notification and which site to receive notifications for.

I can look into this and create a PR, if you are interested in my help!

- Bests,
Osman.

**Comment by aaaeka** [comment]
Hi,
That's definitely a feature I will add in the near future after I am finished with the more in-depth info page.
